default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: administrator
  password: administrator

development:
  <<: *default
  database: mudanzas_development

test:
  <<: *default
  database: mudanzas_test

production:
  <<: *default
  database: mudanzas_production
